# Generated by Django 4.2.5 on 2023-09-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=50)),
                ("restaurant_id", models.CharField(max_length=20)),
                ("food_name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="food_images/")),
            ],
        ),
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonenumber", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("phonenumber", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("mailid", models.CharField(max_length=50, unique=True)),
                ("pincode", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("profile_pic", models.ImageField(null=True, upload_to="food_images/")),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="restro.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("phonenumber", models.CharField(max_length=15)),
                ("mailid", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="restro.login"
                    ),
                ),
            ],
        ),
    ]
