# Generated by Django 4.2.5 on 2023-09-22 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restro", "0002_alter_food_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="image",
        ),
    ]
