# Generated by Django 4.2.5 on 2023-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restro", "0003_remove_food_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(null=True, upload_to="food_images/"),
        ),
    ]
