# Generated by Django 4.2.5 on 2023-09-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restro", "0004_food_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(default=1, upload_to="food_images/"),
            preserve_default=False,
        ),
    ]
